language: android
jdk: oraclejdk8

android:
  components:
    - platform-tools
    - tools
    - build-tools-25.0.2
    - android-24
    - extra-android-m2repository

after_success:
 - chmod +x ./upload_apk.sh
 - ./upload_apk.sh

script: cd android_app && ./gradlew assembleDebug
